#!/usr/bin/env python3
"""Generate ``src/python/unicode/tables.rs`` from CPython's ``unicodedata``.

Python's ``str`` predicates and title-case mapping use Unicode properties that Rust's standard
library does not expose: the numeric types behind ``isdecimal``, ``isdigit`` and
``isnumeric``, the title-case letter category, Python's whitespace set, and the title-case
mappings that differ from upper case. ``unicodedata`` does not expose Case_Ignorable, so the
script observes it through ``str.lower``'s final-sigma rule, which is defined by it. The
identifier classes are observed through ``str.isidentifier``. The tables are sorted inclusive
code point ranges.

Run it with the CPython release shellsim models so the Unicode version matches:

    uv run --python 3.14 infra/generate-unicode-tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from collections.abc import Callable
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "src/python/unicode/tables.rs"
PYTHON_VERSION = (3, 14)
MAX_CODE_POINT = 0x110000


def ranges(predicate: Callable[[str], bool]) -> list[tuple[int, int]]:
    """Inclusive code point ranges whose characters satisfy ``predicate``."""

    found: list[tuple[int, int]] = []
    start = None
    for code in range(MAX_CODE_POINT + 1):
        matches = code < MAX_CODE_POINT and predicate(chr(code))
        if matches and start is None:
            start = code
        elif not matches and start is not None:
            found.append((start, code - 1))
            start = None
    return found


def range_table(name: str, doc: str, predicate: Callable[[str], bool]) -> str:
    rows = "".join(f"    ({start:#06x}, {end:#06x}),\n" for start, end in ranges(predicate))
    return f"/// {doc}\npub(super) static {name}: &[(u32, u32)] = &[\n{rows}];\n"


def case_ignorable(character: str) -> bool:
    """Whether CPython skips ``character`` when deciding if a capital sigma ends a word.

    A cased letter before the ignorable run makes the sigma final; an uncased one does not.
    """

    after_cased = ("A" + character + "\u03a3").lower().endswith("\u03c2")
    after_uncased = ("1" + character + "\u03a3").lower().endswith("\u03c3")
    return after_cased and after_uncased


def rust_string(text: str) -> str:
    return '"' + "".join(f"\\u{{{ord(character):x}}}" for character in text) + '"'


def title_table() -> str:
    rows = "".join(
        f"    ({code:#06x}, {rust_string(chr(code).title())}),\n"
        for code in range(MAX_CODE_POINT)
        if chr(code).title() != chr(code).upper()
    )
    return (
        "/// Characters whose full title-case mapping differs from their full upper-case mapping.\n"
        f"pub(super) static TITLE_CASE: &[(u32, &str)] = &[\n{rows}];\n"
    )


def main() -> None:
    if sys.version_info[:2] != PYTHON_VERSION:
        raise SystemExit(f"run with CPython {PYTHON_VERSION[0]}.{PYTHON_VERSION[1]}")
    sections = [
        "//! Unicode property tables for Python `str` predicates and case mapping.\n//!\n"
        "//! Generated by `infra/generate-unicode-tables.py` from CPython "
        f"{sys.version.split()[0]}\n//! (Unicode {unicodedata.unidata_version}). Do not edit.\n",
        range_table("DECIMAL", "Numeric_Type=Decimal: `str.isdecimal`.", str.isdecimal),
        range_table("DIGIT", "Numeric_Type=Decimal or Digit: `str.isdigit`.", str.isdigit),
        range_table("NUMERIC", "Any Numeric_Type: `str.isnumeric`.", str.isnumeric),
        range_table("SPACE", "Python's whitespace: `str.isspace`.", str.isspace),
        range_table(
            "TITLE_LETTER",
            "General category Lt, which Python treats as cased.",
            lambda character: unicodedata.category(character) == "Lt",
        ),
        range_table(
            "CASE_IGNORABLE",
            "Case_Ignorable, which the final-sigma rule skips.",
            case_ignorable,
        ),
        range_table(
            "IDENTIFIER_START",
            "XID_Start and `_`: characters that may begin `str.isidentifier`.",
            str.isidentifier,
        ),
        range_table(
            "IDENTIFIER_CONTINUE",
            "XID_Continue: characters that may follow the first in `str.isidentifier`.",
            lambda character: ("_" + character).isidentifier(),
        ),
        title_table(),
    ]
    OUTPUT.write_text("\n".join(sections))


if __name__ == "__main__":
    main()
