"""Pin integrity plus optional full builds verify unchanged pure-wheel output."""

import hashlib
import json
import os
from pathlib import Path

import pytest

from ports.python.cellpylib.build import _relative, build, sha256, validate_wheel

ROOT = Path(__file__).resolve().parents[4]


def test_pure_sdist_recipe_pins_builder_and_real_dependencies():
    port = ROOT / "ports/python/cellpylib"
    recipe = json.loads((port / "recipe.json").read_text())
    assert recipe["version"] == "2.4.0"
    assert recipe["patches"] == []
    assert set(recipe["requires_dist"]) == {"numpy>=1.15.4", "matplotlib>=3.0.2"}
    assert recipe["wheel"] == "cellpylib-2.4.0-py3-none-any.whl"
    assert sha256(port / "build.py") == recipe["build_script_sha256"]


@pytest.mark.parametrize("path", ["/absolute", "../escape", "a/../escape", "a\\escape", "a\0escape"])
def test_build_archive_path_rejects_escape(path):
    with pytest.raises(ValueError):
        _relative(path)


def test_corrupt_source_rejected_before_build(tmp_path):
    source = tmp_path / "source.tar.gz"
    source.write_bytes(b"corrupt")
    with pytest.raises(ValueError):
        build(source, tmp_path / "missing-tool.whl", tmp_path / "output")
    assert not (tmp_path / "output").exists()


def test_unchanged_pure_wheel_is_reproducible(tmp_path):
    source = os.environ.get("SHELLSIM_CELLPYLIB_SOURCE_ARCHIVE")
    tool = os.environ.get("SHELLSIM_CELLPYLIB_SETUPTOOLS_WHEEL")
    if not source or not tool:
        pytest.skip("set pinned source/tool archive paths for approved sdist builds")
    first = build(Path(source), Path(tool), tmp_path / "first")
    second = build(Path(source), Path(tool), tmp_path / "second")
    assert sha256(first) == sha256(second)
    recipe = json.loads((ROOT / "ports/python/cellpylib/recipe.json").read_text())
    source_root = tmp_path / "first/source/cellpylib-2.4.0"
    original = validate_wheel(first, source_root, recipe)
    assert len(original) == 18
    # The source comparison must reject an altered runtime module, independently
    # of valid wheel RECORD hashes generated by the pinned backend.
    (source_root / "cellpylib/__init__.py").write_text("changed")
    with pytest.raises(ValueError):
        validate_wheel(first, source_root, recipe)
    manifest = json.loads((tmp_path / "second/artifact.json").read_text())
    assert manifest["host_tools"]["setuptools"]["version"] == "84.0.0"
    assert (
        hashlib.sha256(Path(manifest["host_tools"]["python"]["path"]).read_bytes()).hexdigest()
        == (manifest["host_tools"]["python"]["sha256"])
    )
    index = (tmp_path / "second/pure-simple/cellpylib/index.html").read_text()
    assert "#sha256=" + sha256(second) in index
