//! Tokens for the deliberately small, source-compatible Python grammar.

use super::source::Span;

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Name(String),
    Integer(i64),
    BigInteger(String),
    /// A decimal floating-point literal validated by the lexer and stored as an f64.
    Float(f64),
    String(String),
    Bytes(Vec<u8>),
    FString {
        body: String,
        raw: bool,
    },
    Import,
    From,
    As,
    Del,
    None,
    True,
    False,
    And,
    Or,
    Not,
    In,
    Is,
    Plus,
    PlusEqual,
    Minus,
    MinusEqual,
    Arrow,
    Star,
    DoubleStar,
    StarEqual,
    DoubleStarEqual,
    Slash,
    DoubleSlash,
    SlashEqual,
    DoubleSlashEqual,
    Percent,
    PercentEqual,
    Ampersand,
    AmpersandEqual,
    Caret,
    CaretEqual,
    Tilde,
    Pipe,
    PipeEqual,
    Equal,
    EqualEqual,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Dot,
    At,
    Comma,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Colon,
    Semicolon,
    Newline,
    Indent,
    Dedent,
    Eof,
    If,
    Elif,
    Else,
    While,
    For,
    Def,
    Class,
    Lambda,
    Return,
    Break,
    Continue,
    Global,
    Nonlocal,
    Pass,
    Assert,
    Try,
    Except,
    Finally,
    Raise,
    With,
    Yield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
