//! Tokens for the deliberately small, source-compatible Python grammar.

use super::source::Span;

#[derive(Clone, Debug, PartialEq)]
pub enum TokenKind {
    Name(String),
    Integer(i64),
    /// A decimal floating-point literal. The VM has no arbitrary precision
    /// numeric type, so validation happens in the lexer and stores an f64.
    Float(f64),
    String(String),
    FString(String),
    Import,
    From,
    As,
    Del,
    None,
    True,
    False,
    And,
    Or,
    Not,
    In,
    Is,
    Plus,
    PlusEqual,
    Minus,
    MinusEqual,
    Arrow,
    Star,
    Slash,
    DoubleSlash,
    Percent,
    Pipe,
    Equal,
    EqualEqual,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    Dot,
    At,
    Comma,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftBrace,
    RightBrace,
    Colon,
    Semicolon,
    Newline,
    Indent,
    Dedent,
    Eof,
    If,
    Elif,
    Else,
    While,
    For,
    Def,
    Class,
    Lambda,
    Return,
    Break,
    Continue,
    Nonlocal,
    Pass,
    Assert,
    Try,
    Except,
    Finally,
    Raise,
    With,
    Yield,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
}
